name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: true

    - name: Build and Deploy
      uses: solybum/hexo-deploy@master
      env:
        PERSONAL_TOKEN: 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
        PUBLISH_REPOSITORY: https://github.com/Huang-junsen/Junsen-blog.git
        BRANCH: blog
        PUBLISH_DIR: ./public
